- name: Generate TSV
  template:
    src: SongsDLC.tsv.j2
    dest: "{{song_dict['songfolder']}}/SongsDLC.tsv"
   # dest: "{{song_dict['atmospherefolder']}}/contents/{{song_dict['titleid']}}/romfs/Data/StreamingAssets/SongsDLC.tsv"
- name: Generate name.txt
  template:
    src: name.txt.j2
    dest: "{{song_dict['songfolder']}}/name.txt"
    newline_sequence: \r\n
    #dest: "{{song_dict['atmospherefolder']}}/contents/{{song_dict['dlcid']}}/romfs/name.txt"
