- name: Load validation file
  set_fact:
    validationjson: "{{ lookup('ansible.builtin.file', '{{song_dict.songfolder}}/validation.json')}}"
- set_fact:
    singstar_url_changed: False
- name: Validate Song
  include_tasks: check_song.yml
- name: Set complete path and song name
  set_fact:
    songpathname: "{{ song_dict.songfolder }}/{{ song.uid }}/{{ song.uid }}"

- name: Download Mediafiles from Youtube..
  include_tasks: media_download.yml
  when: 
   - singstar_url_changed or ({{song.id}} in {{singstar_force_url}}) or ({{song.id}} in {{singstar_force}})

- name: Copy custom Mediafiles..
  include_tasks: media_custom.yml
#  when: song.customfiles.icon is defined or song.customfiles.background is defined

- name: Register song length
  shell: |
    ffprobe {{ songpathname }}.ogg 2>&1 | grep "Duration"| cut -d ' ' -f 4 | sed s/,// | sed 's@\..*@@g' | awk '{ split($1, A, ":"); split(A[3], B, "."); print 3600*A[1] + 60*A[2] + B[1]}'
  register: song_length

- name: Create Song Meta Files
  include_tasks: generate_song.yml

- name: Move Song files into atmosphere folder
  include_tasks: move_song.yml
