- assert:
    that:
      - song.name is defined
      - song.uid is defined
      - song.id is defined
      - song.url is defined
      - song.genre is defined
      - song.artist is defined
      - song.release is defined
      - song.difficulty is defined
    quiet: true
    success_msg: Everything is defined.
    fail_msg: "Song is missig a variable!"

- name: Init JSON with new data
  set_fact:
    validationjson: "{{ validationjson | combine( {  song.id|string: { 'name': '0', 'txthash': '0', 'url': '0' }  })}}"
  when: validationjson["{{song.id|string}}"] is not defined

- name: Check if URL changed
  set_fact:
    singstar_url_changed: True
  when: (validationjson["{{song.id|string}}"]["url"] != song.url) or ({{song.id}} in {{singstar_force_url}}) or ({{song.id}} in {{singstar_force}})

- assert:
    that: ({{song.id}} in {{singstar_force_url}}) or ({{song.id}} in {{singstar_force}})
    quiet: true
    fail_msg: "The Youtube URL for ID {{ song.id }} has changed. Please force to overwrite the current one"
  when: 
   - singstar_url_changed
   - ({{song.id}} in {{singstar_force_url}}) or ({{song.id}} in {{singstar_force}}) 

- name: Check if TXT changed
  block:
    - stat:
        path: "{{song_dict.songfolder}}/{{song.uid}}/{{song.uid}}.txt"
        checksum_algorithm: md5
        get_checksum: true
      register: singstar_txt
    - set_fact: 
        singstarhash_dict: "{{ singstarhash_dict | default({}) | combine( { song.id: singstar_txt } ) }}"
    - set_fact:
        singstar_txt_changed: True
      when: ({{singstar_txt.stat.checksum != validationjson[song.id|string]['txthash']}}) or ({{song.id}} in {{singstar_force_txt}}) or ({{song.id}} in {{singstar_force}})
    
    - name: Remove VXLA
      file:
        state: absent
        path: "{{song_dict.songfolder}}/{{song.uid}}/{{song.uid}}.vxla"    
      when: ({{singstar_txt.stat.checksum != validationjson[song.id|string]['txthash']}}) or ({{song.id}} in {{singstar_force_txt}}) or ({{song.id}} in {{singstar_force}})

        
 #   - assert:
 #       that: ({{song.id}} in {{singstar_force_txt}}) or ({{song.id}} in {{singstar_force}})
 #       quiet: true
 #       fail_msg: "The TXT has changed. Please force to overwrite the current one"
 #     loop: "{{ lookup('list', song_dict['songs'], wantlist=False) }}"
  #    when: "{{singstar_txt.stat.checksum != validationjson[song.id|string]['txthash']}}"
      